packages:
  - apps/*
  - packages/*

catalog:
  '@astrojs/check': ^0.9.8
  "@astrojs/vue": ^6.0.1
  "@directus/api": "^25.0.1"
  "@directus/extensions-sdk": "^13.1.1"
  "@directus/sdk": "^18.0.3"
  "@iconify-json/mynaui": "^1.2.17"
  "@tiptap/core": "^2.27.2"
  "@tiptap/extension-blockquote": "^2.27.2"
  "@tiptap/extension-bold": "^2.27.2"
  "@tiptap/extension-bullet-list": "^2.27.2"
  "@tiptap/extension-code": "^2.27.2"
  "@tiptap/extension-code-block": "^2.27.2"
  "@tiptap/extension-document": "^2.27.2"
  "@tiptap/extension-dropcursor": "^2.27.2"
  "@tiptap/extension-gapcursor": "^2.27.2"
  "@tiptap/extension-hard-break": "^2.27.2"
  "@tiptap/extension-heading": "^2.27.2"
  "@tiptap/extension-history": "^2.27.2"
  "@tiptap/extension-horizontal-rule": "^2.27.2"
  "@tiptap/extension-italic": "^2.27.2"
  "@tiptap/extension-link": "^2.27.2"
  "@tiptap/extension-list-item": "^2.27.2"
  "@tiptap/extension-ordered-list": "^2.27.2"
  "@tiptap/extension-paragraph": "^2.27.2"
  "@tiptap/extension-placeholder": "^2.27.2"
  "@tiptap/extension-strike": "^2.27.2"
  "@tiptap/extension-table": "^2.27.2"
  "@tiptap/extension-table-cell": "^2.27.2"
  "@tiptap/extension-table-header": "^2.27.2"
  "@tiptap/extension-table-row": "^2.27.2"
  "@tiptap/extension-text": "^2.27.2"
  "@tiptap/html": "^2.27.2"
  "@tiptap/pm": "^2.11.5"
  "@tiptap/vue-3": "^2.11.5"
  "@types/jsdom": ^28.0.0
  "@types/lodash": "^4.17.15"
  "@types/node": "^24.12.0"
  "@types/uuid": "^9.0.8"
  "@vitejs/plugin-vue-jsx": ^5.1.5
  "astro": ^6.0.8
  "cloudflare": "^4.1.0"
  "commander": "^14.0.1"
  "dayjs": "^1.11.20"
  "dotenv": "^17.2.2"
  "eslint": "^10.0.3"
  "fraction.js": "^4.3.7"
  "jiti": "^2.6.1"
  "jsdom": "^28.1.0"
  "lodash": "^4.17.21"
  "minisearch": "^6.3.0"
  "openapi-fetch": "^0.13.8"
  "openapi-typescript": "^7.13.0"
  "oxfmt": "0.43.0"
  "oxlint": "1.56.0"
  "oxlint-tsgolint": ^0.17.2
  "pinia": "2.1.7"
  "pure-rand": "^6.1.0"
  "sass": "^1.98.0"
  "schema-dts": "^1.1.5"
  "tiptap-render-view": "^1.0.4"
  "tsx": "^4.20.6"
  "turbo": "^2.8.20"
  "typescript": "~5.9.3"
  "typescript-eslint": "^8.57.1"
  "uuid": "^9.0.1"
  "validator": "^13.12.0"
  vite: ^8.0.5
  vue: 3.5.30
  "vue-tsc": "^3.2.6"

catalogMode: strict
