packages:
  - apps/*
  - extensions/*
  - packages/*
catalog:
  "@cloudflare/workers-types": "4.20250311.0"
  "@directus/api": "^25.0.1"
  "@directus/extensions-sdk": "^13.1.1"
  "@directus/sdk": "^18.0.3"
  "@iconify-json/mynaui": "^1.2.9"
  "@nuxt/eslint": "0.7.2"
  "@nuxt/fonts": "^0.6.1"
  "@nuxt/icon": "1.13.0"
  "@nuxtjs/robots": "5.2.4"
  "@nuxtjs/sitemap": "^5.3.5"
  "@tiptap/core": "^2.11.5"
  "@tiptap/extension-blockquote": "^2.11.5"
  "@tiptap/extension-bold": "^2.11.5"
  "@tiptap/extension-bullet-list": "^2.11.5"
  "@tiptap/extension-code": "^2.11.5"
  "@tiptap/extension-code-block": "^2.11.5"
  "@tiptap/extension-document": "^2.11.5"
  "@tiptap/extension-dropcursor": "^2.11.5"
  "@tiptap/extension-gapcursor": "^2.11.5"
  "@tiptap/extension-hard-break": "^2.11.5"
  "@tiptap/extension-heading": "^2.11.5"
  "@tiptap/extension-history": "^2.11.5"
  "@tiptap/extension-horizontal-rule": "^2.11.5"
  "@tiptap/extension-italic": "^2.11.5"
  "@tiptap/extension-link": "^2.11.5"
  "@tiptap/extension-list-item": "^2.11.5"
  "@tiptap/extension-ordered-list": "^2.11.5"
  "@tiptap/extension-paragraph": "^2.11.5"
  "@tiptap/extension-placeholder": "^2.11.5"
  "@tiptap/extension-strike": "^2.11.5"
  "@tiptap/extension-table": "^2.11.5"
  "@tiptap/extension-table-cell": "^2.11.5"
  "@tiptap/extension-table-header": "^2.11.5"
  "@tiptap/extension-table-row": "^2.11.5"
  "@tiptap/extension-text": "^2.11.5"
  "@tiptap/html": "^2.11.5"
  "@tiptap/pm": "^2.11.5"
  "@tiptap/vue-3": "^2.11.5"
  "@types/lodash": "^4.17.15"
  "@types/node": "^22.13.10"
  "@types/uuid": "^9.0.8"
  "cloudflare": "^4.1.0"
  "dayjs": "^1.11.13"
  "eslint": "^9.28.0"
  "eslint-config-prettier": "^10.1.5"
  "eslint-plugin-vue": "^10.1.0"
  "fraction.js": "^4.3.7"
  "jiti": "^2.4.2"
  "lodash": "^4.17.21"
  "minisearch": "^6.3.0"
  "nuxt": "3.16.0"
  "nuxt-prepare": "2.3.1"
  "openapi-fetch": "^0.13.4"
  "openapi-typescript": "^7.4.4"
  "pinia": "2.1.7"
  "pure-rand": "^6.1.0"
  "sass": "^1.85.1"
  "schema-dts": "^1.1.5"
  "tiptap-render-view": "^1.0.2"
  "turbo": "^2.5.8"
  "typescript": "^5.7.3"
  "typescript-eslint": "^8.33.1"
  "uuid": "^9.0.1"
  "validator": "^13.12.0"
  "vue": "^3.5.13"
  "vue-i18n": "^9.14.2"
  "vue-tsc": "^2.2.8"
  "wrangler": "4.15.2"
