// <auto-generated />
using System;
using API.Models.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20221204124735_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("NOCASE")
                .HasAnnotation("ProductVersion", "7.0.0-preview.2.22153.1");

            modelBuilder.Entity("API.Models.Database.DbCategory", b =>
                {
                    b.Property<string>("Label")
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Label");

                    b.HasIndex("Label");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("API.Models.Database.DbCuisine", b =>
                {
                    b.Property<string>("Label")
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Label");

                    b.HasIndex("Label");

                    b.ToTable("Cuisines");
                });

            modelBuilder.Entity("API.Models.Database.DbCustomTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("CookingTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomTimeLabelLabel")
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int?>("DbRecipeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomTimeLabelLabel");

                    b.HasIndex("DbRecipeId");

                    b.ToTable("CustomTimes");
                });

            modelBuilder.Entity("API.Models.Database.DbCustomTimeLabel", b =>
                {
                    b.Property<string>("Label")
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Label");

                    b.ToTable("CustomTimeLabels");
                });

            modelBuilder.Entity("API.Models.Database.DbIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DbIngredientGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("DbIngredientGroupId");

                    b.HasIndex("Name");

                    b.ToTable("DbIngredient");
                });

            modelBuilder.Entity("API.Models.Database.DbIngredientGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DbRecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("DbRecipeId");

                    b.ToTable("DbIngredientGroup");
                });

            modelBuilder.Entity("API.Models.Database.DbInstruction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DbInstructionGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("DbInstructionGroupId");

                    b.ToTable("DbInstruction");
                });

            modelBuilder.Entity("API.Models.Database.DbInstructionGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DbRecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("DbRecipeId");

                    b.ToTable("DbInstructionGroup");
                });

            modelBuilder.Entity("API.Models.Database.DbRecipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryLabel")
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<TimeSpan>("CookingTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("CuisineLabel")
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<decimal?>("Energy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<TimeSpan>("PreparationTime")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rating")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Servings")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("CategoryLabel");

                    b.HasIndex("CuisineLabel");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Title");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("API.Models.Database.DbTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Label")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("DbRecipeDbTag", b =>
                {
                    b.Property<int>("RecipesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RecipesId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("DbRecipeDbTag");
                });

            modelBuilder.Entity("API.Models.Database.DbCustomTime", b =>
                {
                    b.HasOne("API.Models.Database.DbCustomTimeLabel", "CustomTimeLabel")
                        .WithMany("DbCustomTimes")
                        .HasForeignKey("CustomTimeLabelLabel");

                    b.HasOne("API.Models.Database.DbRecipe", null)
                        .WithMany("CustomTimes")
                        .HasForeignKey("DbRecipeId");

                    b.Navigation("CustomTimeLabel");
                });

            modelBuilder.Entity("API.Models.Database.DbIngredient", b =>
                {
                    b.HasOne("API.Models.Database.DbIngredientGroup", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("DbIngredientGroupId");
                });

            modelBuilder.Entity("API.Models.Database.DbIngredientGroup", b =>
                {
                    b.HasOne("API.Models.Database.DbRecipe", null)
                        .WithMany("IngredientGroups")
                        .HasForeignKey("DbRecipeId");
                });

            modelBuilder.Entity("API.Models.Database.DbInstruction", b =>
                {
                    b.HasOne("API.Models.Database.DbInstructionGroup", null)
                        .WithMany("Instructions")
                        .HasForeignKey("DbInstructionGroupId");
                });

            modelBuilder.Entity("API.Models.Database.DbInstructionGroup", b =>
                {
                    b.HasOne("API.Models.Database.DbRecipe", null)
                        .WithMany("InstructionGroups")
                        .HasForeignKey("DbRecipeId");
                });

            modelBuilder.Entity("API.Models.Database.DbRecipe", b =>
                {
                    b.HasOne("API.Models.Database.DbCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryLabel");

                    b.HasOne("API.Models.Database.DbCuisine", "Cuisine")
                        .WithMany()
                        .HasForeignKey("CuisineLabel");

                    b.Navigation("Category");

                    b.Navigation("Cuisine");
                });

            modelBuilder.Entity("DbRecipeDbTag", b =>
                {
                    b.HasOne("API.Models.Database.DbRecipe", null)
                        .WithMany()
                        .HasForeignKey("RecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Database.DbTag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("API.Models.Database.DbCustomTimeLabel", b =>
                {
                    b.Navigation("DbCustomTimes");
                });

            modelBuilder.Entity("API.Models.Database.DbIngredientGroup", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("API.Models.Database.DbInstructionGroup", b =>
                {
                    b.Navigation("Instructions");
                });

            modelBuilder.Entity("API.Models.Database.DbRecipe", b =>
                {
                    b.Navigation("CustomTimes");

                    b.Navigation("IngredientGroups");

                    b.Navigation("InstructionGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
